# Generated by Django 2.2.3 on 2019-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dms_name', models.CharField(choices=[('NetDocuments', 'NetDocuments'), ('iManage', 'iManage')], default='iManage', max_length=1000)),
                ('dms_settings', models.CharField(max_length=1024)),
            ],
        ),
    ]
